### ISSUE TITLE
Custom slack actions buttons

### ISSUE THREAD

**Issue by px-dmitry-t** [grafana/oncall#4552] opened 2024-06-18 11:55 UTC
### What would you like to see!

I would like to have the ability to add links as custom buttons to a message.  

### Product Area

Chatops

### Anything else to add?

I'm using links now, but the posts look ugly. see how I did it in alertmanager.
<img width="606" alt="Screenshot 2024-06-18 at 14 53 55" src="https://github.com/grafana/oncall/assets/120722034/c6de455d-416d-4113-a4fb-5c4c5fc3f03a">
vs 
<img width="663" alt="Screenshot 2024-06-18 at 14 54 53" src="https://github.com/grafana/oncall/assets/120722034/a251257c-94bb-434e-84a0-aa00599d18ed">

**Comment by joeyorlando** [comment] 2024-06-19 17:57
thanks for the feature request! I'm going to close this as a duplicate of #4165

**Closed by joeyorlando** 2024-06-19 17:57 UTC
Labels: feature request, part:chatops, needs triage
