### ISSUE TITLE
API endpoints and query parameters missing for Grafana Oncall

### ISSUE THREAD

**Issue by karengermond** [grafana/oncall#652] opened 2022-10-14 17:59 UTC
Issue from #docs channel:  https://raintank-corp.slack.com/archives/C5PG2JK8W/p1665767547940539

**Comment by Matvey-Kuk** [comment] 2022-10-19 08:12
@karengermond this is a public repo, copy-pasting initial request from the private slack so it will be visible:


Hi all, unless I am mistaken, I believe the [available docs for Grafana Oncall](https://grafana.com/docs/oncall/latest/oncall-api-reference/) are missing some API endpoints.  I wasn't able to find anyway to pull information about user Teams from the API, until I checked the [open-source repository](https://github.com/grafana/oncall/blob/1b3b0f9e13f2644d3edce0956112097f691c8f9a/engine/apps/public_api/urls.py#L27) and found there was a teams endpoint.

**Comment by joeyorlando** [comment] 2024-06-14 18:41
closing as duplicate of https://github.com/grafana/oncall/issues/2448

**Closed by joeyorlando** 2024-06-14 18:41 UTC
Labels: type/docs, needs triage
