### ISSUE TITLE
Migrate @grafana/toolkit to create-plugin instead

### ISSUE THREAD

**Issue by teodosii** [grafana/oncall#2980] opened 2023-09-06 09:07 UTC
### What went wrong?

We're currently using `@grafana/toolkit` but that package has been deprecated and we should aim at migrating it to `create-plugin` instead as that is the alternative grafana offers

**Comment by maskin25** [comment] 2024-02-02 11:22
duplicate of [Migrate from grafana-toolkit to grafana plugin tools #3651](https://github.com/grafana/oncall/issues/3651), (more precisely, it’s the other way around, but it’s easier for me to close this one :)

**Closed as completed by maskin25** 2024-02-02 11:22 UTC
Labels: bug, involved:Frontend
