### ISSUE TITLE
Search by a title 

### ISSUE THREAD

**Issue by nicolas-fidel-wmx** [grafana/oncall#4263] opened 2024-04-22 09:55 UTC
### What would you like to see!

Add the ability to search by name on the alert group page.

Overall, I find the search function not powerful enough when you have a lot of alerts, it's hard to find your way around.

Is it possible to add custom search options based on the json fields sent by the webhook?

### Product Area

Alert Flow & Configuration

**Comment by joeyorlando** [comment] 2024-04-22 12:30
Closing as a duplicate of #2232 . See [this comment here](https://github.com/grafana/oncall/issues/2232) in that issue for some info to get you started if you'd like to open a PR contribution 🙂

**Closed by joeyorlando** 2024-04-22 12:30 UTC
Labels: feature request, part:alert flow & configuration
