### ISSUE TITLE
User profile: add sort priority to important notifications and rename such settings to Notification policies

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#3936] opened 2024-02-21 13:15 UTC
At the moment we have such view which has wording issues with Notifications as mobile app entity. 

![Image](https://github.com/grafana/oncall/assets/102970268/a478b298-574a-4f1a-8a12-7131f4c0f46b)

Solution - rename it to Notification policies as we already have in mobile.

It also makes sense to add priority to Important policy to show it first.

**Comment by iskhakov** [comment] 2024-03-20 11:41
duplicate of https://github.com/grafana/oncall/issues/3104

**Closed by iskhakov** 2024-03-20 11:41 UTC
Labels: involved:Frontend
