### ISSUE TITLE
Error connecting to onCall - On a kubernetes cluster

### ISSUE THREAD

**Issue by mboujaha** [grafana/oncall#115] opened 2022-06-20 10:35 UTC
Hello everyone,

I have an existing kubernetes cluter with grafana already running, and today i installed Oncall using the helm chart provided in the repository.
The Oncall chart has been installed successfully in a different namespace than grafana.
When i try to configure the Oncall plugin on grafana i get the following error message, even though everything has been set properly

```
Tried connecting to OnCall: http://release-oncall-engine.oncall.svc.cluster.local:8080
Error: Request failed with status code 404, retry or check settings & re-initialize
```

Thank you

**Comment by andy812** [comment] 2022-06-20 13:14
@mboujaha could you paste the output of
`kubectl get svc -n oncall -o wide`

**Comment by dyvol777** [comment] 2022-07-01 00:34
You need to restart grafana. After that everything is ok

**Comment by mderynck** [comment] 2022-07-05 19:58
@mboujaha Was this resolved by restarting Grafana?

**Comment by Matvey-Kuk** [comment] 2022-07-13 22:06
@mderynck coudl you please try reproducing this? If the grafana restart is required there it worth mentioning in the docs...

**Comment by mttradebyte** [comment] 2022-07-14 09:15
For what it's worth, a restart **was** required when installing the plugin via the UI due to an existing Grafana bug.

**Comment by mderynck** [comment] 2022-07-14 19:12
https://github.com/grafana/oncall/pull/236

**Closed** 2022-07-20 10:02 UTC
Labels: bug, deployment
