### ISSUE TITLE
Unable to assign a team to an integration

### ISSUE THREAD

**Issue by carozuniga** [grafana/oncall#2082] opened 2023-06-01 15:08 UTC
Hello, this is happening on Grafana Cloud, I'm unable to assign a team to any integration for an already created integration. 
Steps to reproduce the issue:
1. Go to grafana on call integrations
2. Click on any integration with "no team" 
3. Click on the settings gear button
4. Go to settings
5. On the on call team dropdown, select any team 
6. Click on Save, and then save now
7. Nothing happens, the integration is still left with "no team" 

Expected result: The integration should appear with the selected team assigned.

**Comment by romanskugarevLMRU** [comment] 2023-06-20 10:07
+

**Comment by Matvey-Kuk** [comment] 2023-06-23 10:20
Hi! I hope it will be fixed in the upcoming refactoring of alert flow configuration.

**Comment by vadimkerr** [comment] 2023-07-18 20:48
I'm unable to reproduce this on [v1.3.14](https://github.com/grafana/oncall/releases/tag/v1.3.14)

**Closed by vadimkerr** 2023-07-18 20:48 UTC
Labels: bug, part:alert flow & configuration
