### ISSUE TITLE
Release seem often inconsistent

### ISSUE THREAD

**Issue by bpedersen2** [grafana/oncall#3529] opened 2023-12-07 13:39 UTC
### What went wrong?

**What happened**:
- The releases for  oncall helm chart and the  grafana plugin are getting out of sync, both against each other and  against the releases on this repo.

 As of 7.12.2023 (14:35 CEST) i can see:
-  grafana plugin 1.3.62 
- helm chart 1.3.64
- released here 1.3.74
 

**What did you expect to happen**:
- Syncronized releases

### Grafana OnCall Version

v1.3.62/1.3.64

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

releated to #3376 ?

**Comment by joeyorlando** [comment] 2023-12-08 16:08
closing as the downstream root cause in `grafana/helm-charts` was patched in https://github.com/grafana/helm-charts/pull/2828. The next release should properly trigger a release of the helm chart.

**Closed by joeyorlando** 2023-12-08 16:08 UTC
Labels: bug, part:deployment/helm
