### ISSUE TITLE
Option to enable sending resolved messages

### ISSUE THREAD

**Issue by MSommer95** [grafana/oncall#3984] opened 2024-02-29 17:13 UTC
### What would you like to see!

Hey, 
it would be very helpful for us if we could enable an option (Maybe on an integration level) that would allow OnCall to send a message if a firing alert has been resolved or acknowledged (both automatically resolved/acknowledged and manually resolved/ackowledged). 

Our use case would be that not everyone in the escalation chain would have to check into OnCall to see if the alert has already been dealt with. 
This is especially helpful for Email notifications, since its a less dynamic medium compared to Teams channel where you could react to an alert and signal every user that way that the alert has been acknowledged. 

### Product Area

Alert Flow & Configuration

**Comment by roock** [comment] 2024-04-05 11:31
probably a duplicate of #3057

**Comment by joeyorlando** [comment] 2024-06-14 17:56
closing as a duplicate of #3057

**Closed by joeyorlando** 2024-06-14 17:56 UTC
Labels: feature request, part:alert flow & configuration, needs triage
