### ISSUE TITLE
Search doesn't work in Alert Groups page

### ISSUE THREAD

**Issue by marganellim** [grafana/oncall#3030] opened 2023-09-16 22:13 UTC
### What went wrong?

**What happened**:
- When putting a search string into the search text box, the alert group table does not update with the search results

**What did you expect to happen**:
- In the previous version of the grafana on-call plugin, the search function would update the alert groups table with search results

![image](https://github.com/grafana/oncall/assets/82058625/59eeff39-1b91-41f0-ac77-1503a78237e0)

### How do we reproduce it?

1. On the Alert Groups page, type a search string into the search text box
2. Wait for Alert Groups to update with search results

### Grafana OnCall Version

1.3.36

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Other

### User's Browser?

Brave

**Comment by ToonTijtgat2** [comment] 2023-09-18 09:21
+1

**Comment by ToonTijtgat2** [comment] 2023-09-18 09:25
For our setup, the search function never adapted table with the search value.

**Comment by Matvey-Kuk** [comment] 2023-09-18 10:29
We're going to update this part of the product (including search) soon: https://github.com/grafana/oncall/issues/2853

**Comment by marganellim** [comment] 2023-09-27 16:51
Is there any estimate on when the next rev will be released? The broken search is causing alot of headach with a client of ours.

**Comment by marganellim** [comment] 2023-10-18 15:54
Search is still not  working with version 1.3.44

**Comment by vdombrovski** [comment] 2024-01-15 13:16
Can confirm, search still broken in v1.3.86.

From the code, the relevant search function is implemented here:

https://github.com/grafana/oncall/blob/898d025d0982e0f3774d9e772745ffbc61cb66a9/engine/apps/public_api/views/alerts.py#L43

However, looking at the MySQL log, no CAST is actually sent as part of the SQL query, which means that maybe the search request parameter is not passed to the API as expected. (Django casts should be done on the DB-side).

```
MariaDB [(none)]> select * from mysql.general_log where argument like '%CAST%'  \G;
Empty set (0.013 sec)
```

**Comment by marganellim** [comment] 2024-01-20 20:10
Bumping this issue. Is there any resolution coming to the search function?

**Comment by joeyorlando** [comment] 2024-01-29 12:52
This was temporarily disabled in #2101 for performance reasons. We are open to pull requests to conditionally enable this functionality under a feature flag! Something like this should get you started:

`engine/apps/api/views/alert_group.py`
```python3
class AlertGroupView:
   ...
   search_fields = ["=public_primary_key", "=inside_organization_number", "web_title_cache"] if settings.FEATURE_ENABLE_ALERT_GROUP_SEARCH else []
   ...
```

**Comment by ToonTijtgat2** [comment] 2024-01-30 08:14
@joeyorlando thanks for sharing the reason.
Is there a plan to activate it again?

**Comment by joeyorlando** [comment] 2024-01-30 12:53
@ToonTijtgat2 eventually yes! But in the mean time, we're open to reviewing pull requests 😄 (the code snippet above gets you 90% of the way there)

**Comment by joeyorlando** [comment] 2024-03-06 11:08
closing as duplicate of #2232

**Closed by joeyorlando** 2024-03-06 11:08 UTC
Labels: bug, part:alert flow & configuration

**Comment by marganellim** [comment] 2024-03-06 17:09
Does the fact this has been closed as "not planned" indicate you have no plans to have a search function? Are you removing the search feature entirely?

**Comment by joeyorlando** [comment] 2024-03-06 18:01
No plans to remove the search functionality, simply doing some cleanup on our issues and closing this as a duplicate. Feel free to continue the conversation over there!

If you _really_ would like to have this re-enabled, I proposed an potential approach for a PR in [my comment above](https://github.com/grafana/oncall/issues/3030#issuecomment-1914637329), that would allow users to opt-in to having this enabled (disabled by default). If you're willing to create a PR, I will help make sure it gets across the finish-line 😄
