### ISSUE TITLE
Integration menu inconsistency

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#4081] opened 2024-03-18 23:59 UTC
### What went wrong?

**What happened**:
- The context menu on the integrations page does not have the same options available that you have when you select the integration.

In the integration:
![Screenshot from 2024-03-18 17-54-35](https://github.com/grafana/oncall/assets/28077050/e167e216-7830-473e-90a7-7f1374218521)

On the integration table:
![Screenshot from 2024-03-18 17-54-45](https://github.com/grafana/oncall/assets/28077050/1133fdaa-3e99-4946-9c45-14bee3c4e39a)

**What did you expect to happen**:
- I should be able to access all options from both menus since the context is the same integration
- Saves the click from navigating into the integration when editing templates.

### How do we reproduce it?

1. Navigate to Integrations page, options are not available when compared with selecting the integration and using the menu in the top right corner.

### Grafana OnCall Version

r338-v1.3.112

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

I use Grafana Cloud

**Comment by iskhakov** [comment] 2024-03-20 11:39
Duplicate of https://github.com/grafana/oncall-private/issues/2550

**Closed by iskhakov** 2024-03-20 11:39 UTC
Labels: bug, part:alert flow & configuration, involved:Frontend
