### ISSUE TITLE
In the mobile app, I am not getting any sounds for critical alerts 

### ISSUE THREAD

**Issue by doanbutar** [grafana/oncall#3579] opened 2023-12-16 06:43 UTC
### What went wrong?

**What happened**:
I tried configuring the grafana app, but I am failing to get one requirement working.
I want the app to notify (with sound) for critical alerts. I do get the **notifications**, but I'm not getting any **sound**. Interestingly, a colleague of mine did manage to get this behavior correct.

**Additional context**:
Good to emphasize that the android app notification is received by the android app. It's just that the app does not make any notification **sound** when the phone is set to **silent** (even though I've followed the configuration procedure for the app to make a sound even when the phone is set to silent). Also good to emphasize that exactly the same notification is received (with sound) on an (android) phone of a colleague. 

**What did you expect to happen**:
Getting a sound for the critical alert even though the phone is set to silent

### How do we reproduce it?

1. Send a push notification for important alerts.
2. Add mobile app to notification policies
3. Override do not disturb
4. Override system volume

### Grafana OnCall Version

Android app

### Product Area

Mobile App

### Grafana OnCall Platform?

I use Grafana Cloud

### Anything else to add?

Attached screenshots
<img width="195" alt="Screenshot 2023-12-16 at 14 41 50" src="https://github.com/grafana/oncall/assets/38452094/b45b2cb2-e428-4a14-9f30-5a8cc0c3667b">
<img width="190" alt="Screenshot 2023-12-16 at 14 41 56" src="https://github.com/grafana/oncall/assets/38452094/635c265f-f8d8-44f2-b225-5f045b68363c">
<img width="199" alt="Screenshot 2023-12-16 at 14 42 03" src="https://github.com/grafana/oncall/assets/38452094/509b925a-310d-483b-af60-df104c2bbf7b">

**Comment by doanbutar** [comment] 2023-12-16 06:46
I am getting more info about the `app version` and `OS` (plus version), from the user.
I am opening this issue on behalf of the customer.

**Comment by LaurensRietveld** [comment] 2023-12-18 13:34
Additional info for the user where things work well:

- Fairphone (vanilla android)
![Screenshot_20231218-142220](https://github.com/grafana/oncall/assets/988347/904fcd97-5d85-4e4a-9568-e156c984c35f)
![Screenshot_20231218-142313](https://github.com/grafana/oncall/assets/988347/8acd175a-4e2f-45b4-9f8f-e76d110e8a8c)

Additional info for the user without sound notification:
- OnePlus 9 PRO
- OxygenOS 13.1

![Screenshot_2023-12-18-14-29-35-46_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/grafana/oncall/assets/988347/567f87a4-a2af-4f56-82f1-7bb8290fad7e)
![Screenshot_2023-12-18-14-29-24-78_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/grafana/oncall/assets/988347/b7a8a9dd-0e2a-424b-8ba9-ab7cf8da603a)
![Screenshot_2023-12-18-14-29-17-00_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/grafana/oncall/assets/988347/abf312cc-864f-4f36-afd1-f1a19fc689a4)

**Comment by imtoori** [comment] 2023-12-19 07:59
Working on this right now, I'll try to reproduce this issue and give updates shortly

**Comment by imtoori** [comment] 2023-12-19 08:34
@LaurensRietveld can you confirm the oneplus 9 pro has the alert slider? 
I'm afraid this could cause some issues with the workaround we use to play sound on silent mode

**Comment by LaurensRietveld** [comment] 2023-12-19 08:36
Hi @imtoori , yes, that one has an alert slider indeed

**Comment by LaurensRietveld** [comment] 2023-12-19 10:38
Note that I also use pushover for different services, which has the option for bypassing silent mode. The mechanism they use works fine

**Comment by imtoori** [comment] 2023-12-19 11:04
We are pushing a small patch that will fix a problem with android not playing sound when the device is in silent mode + DND enabled

I'm not sure this is gonna fix your issue, if it doesn't we're gonna explore other ways.

I hoped this was as easy as it is on iOS, but I'm sure we're gonna find the right workaround.
Thanks a lot for reporting the issue anyways and sorry for the inconvenience.

**Comment by LaurensRietveld** [comment] 2023-12-19 11:15
Great, happy to test the patch :+1:

**Comment by imtoori** [comment] 2024-01-29 06:46
hey @LaurensRietveld 
there have been a couple of updates since we spoke, did you see any progress on your side?

**Comment by imtoori** [comment] 2024-02-09 15:00
I'm gonna close this issue for now, feel free to reopen it in case this is still happening for you!

**Comment by LaurensRietveld** [comment] 2024-02-09 15:14
Sorry for the delay, just tested on version 1.11.1, and I still can't bypass my silent settings (i.e., all notifications remain silent)
When needed, happy to have a videocall or something if that helps  @imtoori

**Comment by imtoori** [comment] 2024-02-09 15:17
I'm quite sure it's due to the issue with the oneplus system :/ 
We'll try to find a solution
I have an old OnePlus with the "alert slider", I'll do some testing and try and find a workaround

**Comment by robert-northmind** [comment] 2024-03-27 14:06
We have located this bug and it has been fixed and is now merged to develop. 
It will be shipped with the v1.16.0 release.
We just uploaded v1.15.0 for beta release, so the beta app for this fix (1.16.0) should be available in about 1 week.

**Closed by robert-northmind** 2024-03-27 14:06 UTC
Labels: bug, part:mobile

**Comment by MedAzizTousli** [comment] 2024-11-05 06:07
Hello guys. Where can I find this v1.16.0 release? The latest release for Grafana OnCall that I could find is v1.11.6
