### ISSUE TITLE
The search field does not work

### ISSUE THREAD

**Issue by fantom0005** [grafana/oncall#4107] opened 2024-03-25 13:39 UTC
### What went wrong?

**What happened**:
- I fill the “Search” field on the alert-groups page and nothing happens

**What did you expect to happen**:
- The filtered list of alert-groups by title or content

### How do we reproduce it?

0. Up Grafana OnCall locally in the docker. I used this [docker-compose file](https://github.com/grafana/oncall/blob/dev/docker-compose.yml)
1. Send several alerts to OnCall with different titles.
2. Go to http://localhost:3000/a/grafana-oncall-app/alert-groups
3. Try to filter by the search filed.
4. Nothing happen.

### Example
<img width="1184" alt="image" src="https://github.com/grafana/oncall/assets/3921689/f771116b-02e0-41bc-ac4d-9234262c2e93">

Networks
<img width="1512" alt="image" src="https://github.com/grafana/oncall/assets/3921689/b5b1bee6-6910-4924-a9a7-1e5a7df3c0b2">

### Grafana OnCall Version

v1.3.113

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Docker

### User's Browser?

Google Chrome 123.0.6312.58 (Official Build) (arm64)

**Comment by joeyorlando** [comment] 2024-03-26 11:17
closing as duplicate of https://github.com/grafana/oncall/issues/2232

**Closed by joeyorlando** 2024-03-26 11:17 UTC
Labels: bug, part:alert flow & configuration
