### ISSUE TITLE
Support new nav's breadcrumbs

### ISSUE THREAD

**Issue by raphael-batte** [grafana/oncall#1310] opened 2023-02-08 14:03 UTC
We added to OnCall new URL logic but still have one difference from Grafana core and other apps:
We don't place current page to the breadcrumbs 
![image](https://user-images.githubusercontent.com/102970268/217551265-df3ce7f8-c335-415a-8a7c-be32c37b0984.png)

Grafana has such thing:
![image](https://user-images.githubusercontent.com/102970268/217551461-3ab88a68-e1d7-48b6-b436-869b2247ce0c.png)

Will be great to unify breadcrumbs behavior with Grafana.

**Comment by jtheory** [comment] 2023-03-13 17:05
Checking on sedemo -- it looks like both of these issues have been fixed already. @raphael-batte should we close this issue?

**Comment by maskin25** [comment] 2023-07-12 11:58
duplicate of https://github.com/grafana/oncall/issues/1906, so I'm closing

**Closed by maskin25** 2023-07-12 11:58 UTC
Labels: involved:UX, involved:Frontend
