### ISSUE TITLE
Get rid of console errors during unit tests execution

### ISSUE THREAD

**Issue by brojd** [grafana/oncall#3656] opened 2024-01-10 14:30 UTC
We have many console errors during unit tests run which makes it difficult to understand the output. We should get rid of them so it's easy to review test results

Parent issue: [#3650](https://github.com/grafana/oncall/issues/3650)

**Comment by maskin25** [comment] 2024-04-02 10:25
duplicate of https://github.com/grafana/oncall/issues/3428

**Closed by maskin25** 2024-04-02 10:25 UTC
Labels: involved:Frontend
