### ISSUE TITLE
Helm Release 1.3.46 Failed GitHub Actions

### ISSUE THREAD

**Issue by nniehoff** [grafana/oncall#3194] opened 2023-10-25 14:12 UTC
### What went wrong?

**What happened**:
- The current latest version of the helm chart is 1.3.45.

**What did you expect to happen**:
- On release of oncall 1.3.46 the helm chart version 1.3.46 should have also been deployed however the action failed: https://github.com/grafana/oncall/actions/runs/6627353690

### How do we reproduce it?

1. Try to deploy helm chart version 1.3.46 and discover it doesn't exist

### Grafana OnCall Version

1.3.46

### Product Area

Helm, Other

### Grafana OnCall Platform?

None

### User's Browser?

NA

**Comment by bpedersen2** [comment] 2023-10-26 11:09
1.3.47 is also missing both helm chart updates and docker image

**Comment by bpedersen2** [comment] 2023-10-26 11:15
The 1.3.47 helmchart pull request is blocked due to the github bot not having a valid CLA, see #3202

**Comment by joeyorlando** [comment] 2023-11-20 23:17
Closing as duplicate of #3376 (btw, this should now be fixed with the 1.3.60 helm release)

**Closed by joeyorlando** 2023-11-20 23:17 UTC
Labels: bug, part:deployment/helm, no info or need to discuss
