### ISSUE TITLE
IOS mobile application: volume adjustment for important notifications doesn't work.

### ISSUE THREAD

**Issue by omalko394** [grafana/oncall#3770] opened 2024-01-29 08:36 UTC
### What went wrong?

**What happened**:
- Couldn't adjust the level of volume for important notifications in Mobile app for IOS. Decreasing of sound level in app doesn't work - still important notifications alerting with maximum volume.

**What did you expect to happen**:
- Expected that after decreasing of sound level it will change the level of Important alert sound.

### How do we reproduce it?

1. Open Grafana OnCall mobile app on IOS and go to Settings -> Push notifications -> Important notifications.
2. Now drag the slider to decrease level of sound for alert.
3. Send the test important notification to trigger alert on your mobile app with it.

### Grafana OnCall Version

Grafana OnCall: 1.3.81, IOS mobile app: v1.10.3 - build 1364

### Product Area

Mobile App

### Grafana OnCall Platform?

Kubernetes

**Comment by imtoori** [comment] 2024-01-29 08:54
Hi and thanks for the reporting the bug!
I'm trying to reproduce it, but it's working fine for me. I'm on the latest version though (1.11.0)
I'll try using the version your using and come back with more info

**Comment by imtoori** [comment] 2024-01-29 09:16
Still working fine, my suspicion is that in your case there might be something wrong with saving the settings in the backend... I don't see another explanation right now.
Could you try changing the sound and see if that works?

**Comment by imtoori** [comment] 2024-02-09 15:00
I'm gonna close this issue for now, feel free to reopen it in case this is still happening for you!

**Comment by Tonkonozhenko** [comment] 2024-03-15 12:00
@imtoori I've tried to change sounds and volume, but it's still on max and default sound "Small Miracle" even none of default and important notifications has this sound

**Comment by imtoori** [comment] 2024-03-15 12:07
hey @Tonkonozhenko can you elaborate more?
are you saying you don't get the sound or the sound doesn't get changed or what else? Sorry but it's not super clear

**Comment by Tonkonozhenko** [comment] 2024-03-15 12:20
@imtoori sure) I get the sound always on max volume and with "Small Miracle" song

**Comment by imtoori** [comment] 2024-03-15 12:21
That's on iOS right?

**Comment by imtoori** [comment] 2024-03-15 12:21
That's on iOS right?

**Comment by Tonkonozhenko** [comment] 2024-03-15 12:29
@imtoori yes

**Comment by Tonkonozhenko** [comment] 2024-03-15 12:30
@imtoori ![image](https://github.com/grafana/oncall/assets/1307646/76551c5c-f398-4909-b953-407769af80e8) ![image](https://github.com/grafana/oncall/assets/1307646/5190bc69-a877-4506-b489-b84fd4e55d0e)

**Comment by imtoori** [comment] 2024-03-15 13:49
I managed to reproduce the behaviour, thanks a lot for reporting the bug, I'll post updates as soon as possible

**Comment by Tonkonozhenko** [comment] 2024-03-15 13:54
@imtoori thank you so much! I'll be waiting

**Comment by imtoori** [comment] 2024-03-18 10:21
I discovered there were some missing files on ios, they were in the codebase, but they were not properly added to the xcode project.
The fix will be in the upcoming release 1.14.1
I'll close this issue for now, let me know if you find it even in that release
Thanks again for reporting the bug!

**Closed by imtoori** 2024-03-18 10:21 UTC
Labels: bug, part:mobile

**Comment by Tonkonozhenko** [comment] 2024-03-18 15:14
@imtoori thank you! I'll get back when get the update.

**Comment by Tonkonozhenko** [comment] 2024-04-10 10:21
@imtoori unfortunately, the problem is still present

**Comment by imtoori** [comment] 2024-04-10 10:55
@Tonkonozhenko 
so you change the volume in the settings and the notification is still super loud? 
I'm struggling with reproducing the issue, what app version are you using? Also what ios version? 
Thanks for the collaboration
