### ISSUE TITLE
versioning scheme makes installing with grafana-cli unintuitive

### ISSUE THREAD

**Issue by thomasmitchell** [grafana/oncall#1153] opened 2023-01-18 18:55 UTC
Grafana OnCall is unique in that it versions with a `v1.2.3` scheme, whereas nearly all other plugins for Grafana drop the `v` and just have a `1.2.3` versioning scheme. I suppose that because of this norm, the `grafana-cli` strips the leading `v` before passing the version in the URL, and therefore, you cannot install a specific version of the `grafana-oncall-app` plugin from the command line.

The function that strips the `v` in `grafana-cli` can be found here: https://github.com/grafana/grafana/blob/7f4b2fcb9c523e0ebb2842b9df014d3502a96943/pkg/plugins/repo/service.go#L176

This presents an issue in containerized environments where we're trying to scale Grafana horizontally, and therefore want to avoid attaching persistent disk to the Grafana containers. We would use the GF_INSTALL_PLUGINS environment variable of the Grafana docker image to install plugins at startup - this environment variable just calls the `grafana-cli plugins install <plugin> [<version>]` command for each comma-separated value. However, it can't support Grafana OnCall because of the versioning scheme. 

The inability to lock versions is problematic because the plugin version appears to require remaining in lockstep with the backend engine version of OnCall, and as such, restarts of Grafana can break the plugin by upgrading it (or downgrading it, in the case that the newest version is not on the plugin registry yet).

Arguably, this is actually a bug with `grafana-cli`, as the Grafana team does not appear to document a requirement that plugins not start with `v`, but given that changing this behavior could be seen as a breaking change to that project, I'd first like to file this issue to ask how feasible it would be to change the versioning scheme for this project moving forward in order to match other Grafana plugins.

**Comment by thomasmitchell** [comment] 2023-01-18 19:00
You know, now that I've written this out and found the relevant code to do so, I'm realizing that the "version normalizing" function is not very smart - as such... giving it `vv1.2.3` would probably make it do what I want. I'm going to test that now and report back.

**Comment by thomasmitchell** [comment] 2023-01-18 19:07
`grafana-cli plugins install grafana-oncall-app vv1.1.14` actually works! I hate that that works but it does work!

I'm going to leave this issue open - you can close it if you'd like, but if changing the versioning scheme is trivial, then it would still normalize it's behavior with other plugins, and that is still useful.

**Comment by kuzaxak** [comment] 2023-05-21 11:44
This schema isn't supported by grafana operator, I think plugin should use unifiend semver as any other grafana plugin.

**Comment by kuzaxak** [comment] 2023-05-21 11:45
@matiasb could you please have a look?

**Comment by joeyorlando** [comment] 2023-06-27 11:22
closing as a duplicate of #458. please follow that issue for updates on this 😄

**Closed by joeyorlando** 2023-06-27 11:22 UTC
