### ISSUE TITLE
If a user's "Important Notifications" settings are empty, it should inherit their "Default Notifications" 

### ISSUE THREAD

**Issue by eskirk** [grafana/oncall#1138] opened 2023-01-13 21:03 UTC
**What happened:**
I was not paged during an incident even though my "Default Notifications" had options for SMS, slack, and phone call

**What I expected to happen:**
Even in the event of an "important" incident, my default notifications settings should be used to contact me

**Details**
Title - yesterday I was not paged due to my "important notifications" settings being empty. Other members of my team were also under the impression that only filling out "default notifications" should be sufficient and asked that as part of our incident PIR we file a feature request regarding this behavior.

**Comment by PhantomPhreak** [comment] 2023-01-18 03:25
+1

**Comment by greatvovan** [comment] 2023-05-24 18:18
"All" is pretty rad. The one method we reliably have is email (other may be just not configured for a user). Even if the template for email is empty, the message will contain information about the source of email and a link to the issue.

I personally don't like any implicit configuration derivation, it tends to create more confusion than avail.

Let's create every new user with Default and Important flows set to email. Plus maybe do not allow users to clear it completely (currently you can put "Wait 60 s" as a single element). That seems reliable enough in terms of delivery (after all, everyone has email notifications, too) and will help users realize that the personal flow should be reconfigured for the next time.

**Comment by joeyorlando** [comment] 2024-06-17 13:54
Closing as duplicate of #1511

**Closed by joeyorlando** 2024-06-17 13:54 UTC
Labels: feature request, part:alert flow & configuration, needs triage
