### ISSUE TITLE
TopNav warning outside Page component   

### ISSUE THREAD

**Issue by torkelo** [grafana/oncall#982] opened 2022-12-13 07:47 UTC
Nothing should be placed outside the PluginPage component, this warning looks to be outside 

![Screenshot from 2022-12-13 08-45-51](https://user-images.githubusercontent.com/10999/207256501-d18a15ab-aa74-498d-928e-90be489ea8c6.png)

**Comment by Matvey-Kuk** [comment] 2022-12-13 12:41
@maskin25 could you please take a look? New nav 🤣

**Comment by raphael-batte** [comment] 2022-12-19 12:50
Upd to FE in Figma https://www.figma.com/file/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=5310%3A109664&t=h3qXWrpGqXkNfNC9-1

**Comment by teodosii** [comment] 2022-12-21 06:58
This is a duplicate of #904 - let's close this one and use the other one - will copy Raphael's link

**Closed** 2022-12-21 06:59 UTC
Labels: bug, ux/ui
