### ISSUE TITLE
Render resolution notes links in web UI

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#4231] opened 2024-04-15 19:46 UTC
### What would you like to see!

Currently links added in resolution notes are not clickable in the Web UI. The links can be clicked in Slack.  These links should be able to be detected and made clickable.

### Product Area

Alert Flow & Configuration

**Comment by iskhakov** [comment] 2024-05-20 13:24
duplicate of https://github.com/grafana/oncall/issues/505

**Closed** 2024-06-24 19:19 UTC
Labels: bug, feature request, involved:Frontend
