### ISSUE TITLE
Oncall won't connect to slack integration: SSL Error

### ISSUE THREAD

**Issue by Darius-Neagoe** [grafana/oncall#3023] opened 2023-09-14 08:23 UTC
### What went wrong?

**What happened**:
- OAuth fails to authenticate everytime

**What did you expect to happen**:
- OAuth authenticates the user and Oncall creates the SLack integration

### How do we reproduce it?

1. Open Grafana OnCall and try to install the slack integration
2. Now click the "Allow" button on the slack connection page
3. Wait for the browser to redirect you to the main Oncall Page.
4. The URL changes to "/a/grafana-oncall-app/chat-ops&slack_error=auth_failed"
5. Engine Log reports the following:

2023-09-14 08:14:24 source=engine:app google_trace_id=none logger=apps.social_auth.middlewares SocialAuthAuthCanceledExceptionMiddleware.process_exception: Authentication failed: HTTPSConnectionPool(host='[slack.com](http://slack.com/)', port=443): Max retries exceeded with url: /api/oauth.v2.access (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))

I have mounted the Certificates on the docker Volumes too.
REQUESTS_CA_BUNDLE: /var/lib/oncall/rocket-media.cabundle

Docker Compose file:
`version: "3.9"

x-environment: &oncall-environment
  DATABASE_TYPE: sqlite3
  BROKER_TYPE: redis
  BASE_URL: $DOMAIN
  SECRET_KEY: $SECRET_KEY
  FEATURE_PROMETHEUS_EXPORTER_ENABLED: $FEATURE_PROMETHEUS_EXPORTER_ENABLED
  FEATURE_SLACK_INTEGRATION_ENABLED: $FEATURE_SLACK_INTEGRATION_ENABLED
  SLACK_CLIENT_OAUTH_ID: $SLACK_CLIENT_OAUTH_ID
  SLACK_CLIENT_OAUTH_SECRET: $SLACK_CLIENT_OAUTH_SECRET
  SLACK_SIGNING_SECRET: $SLACK_SIGNING_SECRET
  SLACK_INSTALL_RETURN_REDIRECT_HOST: $SLACK_INSTALL_RETURN_REDIRECT_HOST
  SLACK_VERIFICATION_TOKEN: $SLACK_VERIFICATION_TOKEN
  PROMETHEUS_EXPORTER_SECRET: $PROMETHEUS_EXPORTER_SECRET
  SEND_ANONYMOUS_USAGE_STATS: $SEND_ANONYMOUS_USAGE_STATS
  GRAFANA_CLOUD_ONCALL_HEARTBEAT_ENABLED: $GRAFANA_CLOUD_ONCALL_HEARTBEAT_ENABLED
  REDIS_URI: redis://redis:6379/0
  DJANGO_SETTINGS_MODULE: settings.hobby
  CELERY_WORKER_QUEUE: "default,critical,long,slack,telegram,webhook,retry,celery"
  CELERY_WORKER_CONCURRENCY: "1"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "100"
  CELERY_WORKER_SHUTDOWN_INTERVAL: "65m"
  CELERY_WORKER_BEAT_ENABLED: "True"
  GRAFANA_API_URL: $GRAFANA_API_URL
  REQUESTS_CA_BUNDLE: /var/lib/oncall/rocket-media.cabundle

services:
  engine:
    image: grafana/oncall
    restart: always
    ports:
      - "8080:8080"
    command: >
      sh -c "uwsgi --ini uwsgi.ini"
    environment: *oncall-environment
    volumes:
      - oncall_data:/var/lib/oncall
      - /etc/ssl/certs/rocket-media.cabundle:/var/lib/oncall/rocket-media.cabundle
    depends_on:
      oncall_db_migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  celery:
    image: grafana/oncall
    restart: always
    command: sh -c "./celery_with_exporter.sh"
    environment: *oncall-environment
    volumes:
      - oncall_data:/var/lib/oncall
      - /etc/ssl/certs/rocket-media.cabundle:/var/lib/oncall/rocket-media.cabundle
    depends_on:
      oncall_db_migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  oncall_db_migration:
    image: grafana/oncall
    command: python manage.py migrate --noinput
    environment: *oncall-environment
    volumes:
      - oncall_data:/var/lib/oncall
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.0.5
    restart: always
    expose:
      - 6379
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  oncall_data:
  redis_data:`

### Grafana OnCall Version

latest

### Product Area

Chatops

### Grafana OnCall Platform?

Docker

### User's Browser?

Chrome Version 116.0.5845.188 

### Anything else to add?

-

**Comment by iskhakov** [comment] 2024-04-02 11:57
the problem is specific to external certificates. Closing as can't repro

**Closed by iskhakov** 2024-04-02 11:57 UTC
Labels: bug, part:chatops
