### ISSUE TITLE
add support for Grafana Service Account authnz

### ISSUE THREAD

**Issue by SuzumiyaCC** [grafana/oncall#1992] opened 2023-05-23 10:48 UTC
Good afternoon

Please update the oncall plugin to work with Grafana version 9.5.2

The main problem is that the API keys have been replaced with service accounts. When trying to generate a service token for a service account and put it in the .env file

as a secret key - the integration refuses to work.

Please update the plugin and instructions for working with Oncall for the latest versions of grafana

**Comment by joeyorlando** [comment] 2023-06-27 11:29
I was able to reproduce this locally.

**Steps to reproduce**
Running Grafana v10.1.0-56247pre (e3e8a7965a) and Grafana OnCall v1.3.1

1. Configure the plugin as you normally would. This will create a Grafana API Key. 
2. Go to the Grafana "API Keys" page (`/org/apikeys`).
3. Find the "OnCall" API Key that was auto-generated during plugin provisioning and click "Migrate to service account".
4. Go back to OnCall, the plugin returns various error messages. Removing the current plugin configuration and re-configuring also does not seem to resolve the issue.

**Comment by joeyorlando** [comment] 2023-06-27 11:31
closing as a duplicate of #1806. Feel free to watch that issue for updates 😄

**Closed by joeyorlando** 2023-06-27 11:31 UTC
Labels: bug, part:deployment/helm
