### ISSUE TITLE
Plugin Version 1.3.105 missing in Grafana

### ISSUE THREAD

**Issue by MarcoJ-CID** [grafana/oncall#3925] opened 2024-02-20 05:28 UTC
### What went wrong?

**What happened**:
- We updated OnCall to version 1.3.105 and were not able to update the Grafana Plugin.

**What did you expect to happen**:
- That the Version update is for the plugin available as well. We're missing the Plugin Version 1.3.103, 1.3.104 and 1.3.105

### How do we reproduce it?

1. Open Grafana OnCall Plugin Version overview
2. Check available versions

### Grafana OnCall Version

1.3.105

### Product Area

Other

### Grafana OnCall Platform?

Docker

### User's Browser?

Chrome 

### Anything else to add?

Our Grafana is running in Version 10.3.3 (before it was 10.3.1) 
![image](https://github.com/grafana/oncall/assets/6771839/53ff5b46-c3f9-4500-ab40-a9264c8f0278)

**Comment by bpedersen2** [comment] 2024-02-20 08:16
duplicate of #3921

**Comment by joeyorlando** [comment] 2024-02-20 08:29
closing as a duplicate of https://github.com/grafana/oncall/issues/3921 (I will take a look at this issue)

**Closed by joeyorlando** 2024-02-20 08:29 UTC
Labels: bug, no info or need to discuss
