### ISSUE TITLE
[Schedules] Invalid Date

### ISSUE THREAD

**Issue by helmecke** [grafana/oncall#1339] opened 2023-02-17 14:04 UTC
Hi, I've created a schedule via gui. The created schedules is not usable and all elements show invalid date. Current OnCall version is 1.1.24 and Grafana 9.3.6. But the problem was present with older versions. 

![image](https://user-images.githubusercontent.com/37172067/219672937-0d5afefb-71cb-4414-9bb9-b75a57a5cc26.png)

![image](https://user-images.githubusercontent.com/37172067/219673166-45124e76-6ccc-4afe-b2dc-05426d02fc1b.png)

```
An unexpected error happened
Details
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

    at sw (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1942598)
    at li
    at eval (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1951483)
    at n (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1691490)
    at ul
    at eval (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1951524)
    at n (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1677343)
    at div
    at div
    at d (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1878:6289)
    at u (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1878:7047)
    at div
    at Hw (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1952205)
    at div
    at div
    at d (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1878:6289)
    at u (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1878:7047)
    at div
    at div
    at div
    at d (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1878:6289)
    at u (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1878:7047)
    at div
    at b (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1383177)
    at s (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1374375)
    at t (https://redacted/public/plugins/grafana-oncall-app/module.js:2:122081)
    at t (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1389384)
    at Xw (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1950739)
    at i (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1612316)
    at n (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1969600)
    at div
    at div
    at div
    at d (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1878:6289)
    at u (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1878:7047)
    at div
    at Mf (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1661489)
    at n (https://redacted/public/plugins/grafana-oncall-app/module.js:2:2001986)
    at n (https://redacted/public/build/805.dab4bcdab5a814dbcdba.js:2:1063418)
    at t (https://redacted/public/build/805.dab4bcdab5a814dbcdba.js:2:1060860)
    at t (https://redacted/public/build/805.dab4bcdab5a814dbcdba.js:2:1062881)
    at div
    at div
    at div
    at lO (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1643506)
    at i (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1612316)
    at i (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1612316)
    at i (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1612316)
    at t (https://redacted/public/plugins/grafana-oncall-app/module.js:2:1617240)
    at t (https://redacted/public/build/805.dab4bcdab5a814dbcdba.js:2:1050317)
    at io (https://redacted/public/build/2362.5e93872490cc5d80351e.js:8777:23754)
    at component
    at Suspense
    at c (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1207:301)
    at _c (https://redacted/public/build/2362.5e93872490cc5d80351e.js:8831:350)
    at t (https://redacted/public/build/805.dab4bcdab5a814dbcdba.js:2:1060860)
    at t (https://redacted/public/build/805.dab4bcdab5a814dbcdba.js:2:1062881)
    at main
    at Cd (https://redacted/public/build/2362.5e93872490cc5d80351e.js:8792:6822)
    at t (https://redacted/public/build/805.dab4bcdab5a814dbcdba.js:2:1057478)
    at div
    at o (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1996:4308)
    at t.KBarProvider (https://redacted/public/build/805.dab4bcdab5a814dbcdba.js:2:271052)
    at l (https://redacted/public/build/2362.5e93872490cc5d80351e.js:6143:19538)
    at c (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1207:301)
    at u (https://redacted/public/build/2362.5e93872490cc5d80351e.js:1207:855)
    at l (https://redacted/public/build/805.dab4bcdab5a814dbcdba.js:2:1040512)
    at Su (https://redacted/public/build/2362.5e93872490cc5d80351e.js:8844:115)
```

**Comment by helmecke** [comment] 2023-02-20 14:36
Hi @Matvey-Kuk, I'm using the OSS version. The problem seems to be browser based. My default browser is qutebrowser which has this problem but in Firefox it works without issue.

**Comment by teodosii** [comment] 2023-02-23 11:01
@helmecke what OS do you use? I also faced this some time ago, Manjaro/Chromium it was for me. All I was seeing was Invalid Date, but seems I was the only person having this issue :thinking:

**Comment by helmecke** [comment] 2023-02-23 11:49
I'm using Arch currently on `6.1.12-arch1-1`.

**Comment by Matvey-Kuk** [comment] 2023-06-07 10:51
Closing because we updated a lot of the schedules UI recently & can't reproduce. Please re-open if you still face it, thank you!

**Closed by Matvey-Kuk** 2023-06-07 10:51 UTC
Labels: bug, part:schedules, involved:Frontend
