### ISSUE TITLE
Grafana Labs plugin version looks wrong

### ISSUE THREAD

**Issue by atownsend247** [grafana/oncall#1858] opened 2023-05-02 12:06 UTC
This is more about the Grafana Labs plugin, when you look on there now its showing Grafana Oncall listed with a version of `vv1.2.16` this doesn't look right anymore? Has something changed in the ci/cd for it?

- [x] Mention is it's about Cloud or Open Source OnCall. - Affects Both
- [x] Add OnCall backend & frontend versions. `1.2.x` Onwards
- [x] "part:bug"
- [x] `bug`
- [x] Screenshot below 

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/3439514/235661395-f6427f9f-059b-4b68-afbc-a667fa2f2ba6.png">

**Comment by joeyorlando** [comment] 2023-06-27 11:22
closing as a duplicate of #458. please follow that issue for updates on this 😄

**Closed by joeyorlando** 2023-06-27 11:22 UTC
Labels: bug, part:deployment/helm
