### ISSUE TITLE
Grafana OnCall Alert Group Search Not Working

### ISSUE THREAD

**Issue by qubitspace** [grafana/oncall#3716] opened 2024-01-18 17:32 UTC
### What went wrong?

**What happened**:
- Typed in a search term on the grafana oncall alert group page, trying to filter results.

**What did you expect to happen**:
- For it to filter results based on the search term.
- 
![image](https://github.com/grafana/oncall/assets/77802/46ff1049-3c27-4ee3-8331-d7475701125b)

### How do we reproduce it?

1. Open Grafana OnCall and go to alert groups page
2. Enter a search term in the search box
3. Wait for results, but nothing happens

### Grafana OnCall Version

grafana oncall cloud

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment] 2024-01-22 22:03
Closing as duplicate of https://github.com/grafana/oncall/issues/3716

**Comment by joeyorlando** [comment] 2024-01-24 12:57
whoops, linked wrong issue. closing as duplicate of https://github.com/grafana/oncall/issues/3030

**Closed** 2024-01-24 12:58 UTC
Labels: bug, part:alert flow & configuration

**Comment by qubitspace** [comment] 2024-01-26 16:46
I appreciate resolving this, although I don't think it works for me still. Maybe I don't understand what the search field is supposed to do, but it sure seems to do nothing for me. I've tried many search terms and it never changes the results. 

Is the search field, when you type search keywords in it, supposed to filter the results based on the search string? If so I don't think it's working still.
