### ISSUE TITLE
[Helm] External DB using proxies will not work

### ISSUE THREAD

**Issue by lazam** [grafana/oncall#3924] opened 2024-02-19 19:17 UTC
### What went wrong?

**What happened**:
- Using a proxy like `cloud-sql-proxy`, containers will not have a problem since it is used as a sidecar container with a config of localhost. The problem arise due to initContainer `wait-for-db` since it will not connect to an external DB, thus nothing will run. 

**What did you expect to happen**:
- Containers will run successfully even with cloud-sql-proxy.
- There's also no option to disable initContainers
- This check should be at least part of the startup of the app

### How do we reproduce it?

1. Deploy the helm chart with an external DB (RDS, or Google Cloudsql)
2. Use extraContainers for cloud-sql-proxy

### Grafana OnCall Version

1.3.105

### Product Area

Helm

### Grafana OnCall Platform?

None

**Comment by joeyorlando** [comment] 2024-02-20 12:22
closing as a duplicate of

https://github.com/grafana/oncall/issues/1647

**Closed** 2024-02-20 12:22 UTC
Labels: bug, part:deployment/helm
